/* Configuration for final_integration_timing_tests generated by Alire */
#ifndef FINAL_INTEGRATION_TIMING_TESTS_CONFIG_H
#define FINAL_INTEGRATION_TIMING_TESTS_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "final_integration_timing_tests"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
