name = "mnist_test_14x14"
description = "testing dense and quantization on 14x14 mnist"
version = "0.1.0-dev"

authors = ["Dipen R"]
maintainers = ["Dipen R <dipenarathod@gmail.com>"]
maintainers-logins = ["dipenarathod"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
neorv32_hal = "*"
bare_runtime= "*"
wb_npu_helper="*"
input_output_helper = "*"
[[pins]]
neorv32_hal = { path = ".." } 
wb_npu_helper={path ="../wb_npu_helper"}
input_output_helper = {path = "../input_output_helper"}


